### ISSUE TITLE
Instructor-led workshop UI

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1763]
Design and build a new playground-style page to be used for step-by-step codelab workshops.

Basic features:

* Create a new, full-screen page that can accept a codelab's name, location, or other identifying info in its query string.
* On first load, automatically place the initial code state for the workshop into the editor.
* Provide a UI control for advancing and retreating through the steps of the codelab.
  - Each step will have an associated code state, which should automatically be placed into the editor.
* Offer the ability to load the codelab's code from a non-rate-limited source.
  - This means somewhere other than GitHub, essentially. We may need to implement "load from arbitrary URL" to make this happen.

To do:
- [x] Initial UI setup (#1807)
- [x] Authoring guide
- [x] Verify Cloud Storage hosting
- [x] GitHub integration (#1811)
- [x] "Show solution" button (#1819)
- [x] Colorized code snippets in instructions panel (#1829)
- [x] Analyzer / completions (#1834)
- [x] Documentation panel (#1834)
- [x] Hide UI Output in Dart mode (#1834)
- [x] keyboard shortcuts (#1834)
- [ ] Share more code with playground UI (#845)
- [x] Format button (#1834)
- [ ] Run snippet when the step changes
- [x] Get hosting URL for codelabs
- [ ] Add CI to DartPad codelabs in flutter/codelabs
- [ ] Loading UI

Might do:
- [ ] three column layout
- [ ] query parameters for each step (?step=2)
